// Add a Company
POST http://localhost:3000/companies
accept: text/plain
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Cool Company {{$randomInt}}"
}

> {%
 client.global.set("companyId", response.body.entityId)
 client.global.set("correlationId", response.body.correlationId)
 %}

###

// Get a company
GET http://localhost:3000/companies/{{companyId}}
accept: text/plain
#Authorization: Bearer {{auth_token}}
Content-Type: application/json


###


// Add a User
POST http://localhost:3000/{{companyId}}/users
accept: text/plain
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "firstName": "Aaron",
  "lastName": "Thomas",
  "email": "aaron@pop42.com",
  "mobilePhone": "+14802807277"
}

> {%
 client.global.set("userId", response.body.entityId)
 client.global.set("correlationId", response.body.correlationId)
 %}

###


// Get a user
GET http://localhost:3000/{{companyId}}/users/{{userId}}
accept: text/plain
#Authorization: Bearer {{auth_token}}
Content-Type: application/json


###

// Search for users
GET http://localhost:3000/{{companyId}}/users?search=aaron&offset=0&limit=2
accept: text/plain
#Authorization: Bearer {{auth_token}}
Content-Type: application/json


###

// Add a Vehicle
POST http://localhost:3000/{{companyId}}/vehicles
accept: text/plain
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "vehicle #{{$randomInt}}",
  "facilityId": "{{$randomInt}}",
  "vin": "2HGFA1F35BH511718{{$randomInt}}"
}

> {%
 client.global.set("vehicleId", response.body.entityId)
 client.global.set("correlationId", response.body.correlationId)
 %}

###

// Search for vehicles
GET http://localhost:3000/{{companyId}}/vehicles?search=&offset=0&limit=2
accept: text/plain
#Authorization: Bearer {{auth_token}}
Content-Type: application/json


###
